# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/rainviewer/frames"
  to = "/.netlify/functions/rainviewer-frames"
  status = 200

[[redirects]]
  from = "/api/rainviewer/tile/*"
  to = "/.netlify/functions/rainviewer-tile/:splat"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

